Second edition
lidofinance/solido-sdk pull request #2
Opened 2022-07-18 07:36 UTC by j-tulforov

2022-07-19 07:27 UTC, Drujininii approved these changes

2022-07-19 07:27 UTC, Drujininii commented on src/constants.ts
> +  testnet: MAINNET_PROGRAM_ADDRESSES, // TODO change
Friendly reminder)

2022-07-19 07:27 UTC, Drujininii commented on src/index.ts
> +      if (status?.err) {
Как используется tx_stage?

2022-07-19 07:27 UTC, Drujininii requested changes
Давай созвон

2022-07-19 09:20 UTC, Drujininii commented on src/statistics/lidoStatistics.ts
> +  const apy = getStakeApy();
Не нужен ли await?

2022-07-19 13:23 UTC, j-tulforov commented on src/api/defiApy.ts
> +export const getDefiApy = () => 272.14; // TODO change it with api call
https://www.notion.so/Realize-getDefiApy-11915e073c5e45929858e034b4e40ed3

2022-07-19 13:23 UTC, j-tulforov commented on src/statistics/transactionInfo.ts
> +  const transactionCost = await this.getTransactionCost(instruction);
done

2022-07-19 13:25 UTC, j-tulforov commented on src/statistics/lidoStatistics.ts
> +  const marketCap = await this.getMarketCap(totalStaked);
done

2022-07-21 07:55 UTC, Tataklim commented on docz/index.mdx
> +### Using SDK
Тут нужно думаю две решетки, иначе не выносится в отдельный раздел слева

2022-07-21 07:55 UTC, Tataklim commented on docz/index.mdx
> +See [SDK Section](/staking)
Может, какой-то маленький примерчик сюда добавить? Типа того, что в ридми сейчас лежит

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +- *`payerAddress`* - address of user who is trying to make transaction
to make **the** transaction

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +- *`amount`* - SOL amount to stake transaction
Здесь как-то двояко звучит формулировка - мб лучше `amount of SOL to send`?
для следующего метода аналогично

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +_Prepare & return stake transaction (uses Transaction class from @solana/web3.js)_
Prepare**s** & return**s**
аналогично для следующего метода

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +_Sign and confirm stake transaction. Returns transaction hash._
Signs and confirms

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +- *`transaction`* - Ready [@solana/web3.js](https://www.npmjs.com/package/@solana/web3.js) Transaction, got from `getStakeTransaction`.
Мне кажется лучше `prepared transaction from getStakeTransaction `

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +- *`wallet`* - Wallet instance from [@solana/wallet-adapter-base](https://www.npmjs.com/package/@solana/wallet-adapter-base).
У предыдущих параметров ты с маленькой буквы начинал писать определения, а тут с заглавной. А еще есть точки в конце)))

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +_Prepare & return stake transaction (uses Transaction class from @solana/web3.js)_
Может на @solana/web3.js ссылочку добавить? как ниже сделал

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +_Returns exchange rate for stSOL-SOL_
Здесь stSOL, выше StSOL?

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +- *`precision`* - how many decimals leave after . (`default = 4. Example: 1 stSOL = ~1.0485 SOL`)
the number of digits to appear after the decimal point

2022-07-21 07:55 UTC, Tataklim commented on docz/sdk-methods.md
> +_Returns above methods (`exchangeRate`, `transactionCost`, `stakingRewardsFee`) in one place_
`Returns the united response of the previous functions(exchangeRate, transactionCost, stakingRewardsFee)`
а то так звучит, будто должен возвращаться код этих функций

2022-07-21 07:55 UTC, Tataklim commented on docz/stake.mdx
> +Here you can call ready function from SDK:
ready function - что-то не то
мб назвать ее? типа
You can call function `stake` from SDK

2022-07-21 07:55 UTC, Tataklim commented on docz/stake.mdx
> +Or, call sign & confirm methods yourself for total control in transaction stages:
`Or call sign & confirm methods by yourself for total control transaction stages`

2022-07-21 08:00 UTC, Tataklim commented on docz/sdk-methods.md
> +## Transaction info:
Может еще получится какой-то заголовок для всего, что выше ты описал, сделать? чтобы слева оно было в отдельном пункте

2022-07-21 12:42 UTC, j-tulforov commented on docz/stake.mdx
> +Here you can call ready function from SDK:
ну типа готовая функция, готовый метод. Но да, на английском не очень.

2022-07-21 12:43 UTC, j-tulforov commented on docz/sdk-methods.md
> +## Transaction info:
типо для stake & unstake?

2022-07-22 07:31 UTC, Tataklim commented on docz/sdk-methods.md
> +- *`amount`* - SOL amount to stake transaction
кажется, это уже ответ на вопрос, кто получатель))
но в целом не так важно

2022-08-05 13:28 UTC, Drujininii approved these changes

2022-08-05 13:28 UTC, Drujininii approved these changes

2022-08-05 13:29 UTC, merged